// Generates the engine constants and message tables for both cores from shared/*.json.
// Usage: node script/gen_shared.mjs [--check]
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const root = dirname(dirname(fileURLToPath(import.meta.url)));
const mode = process.argv[2] ?? 'write';
if (mode !== 'write' && mode !== '--check') { console.error('Usage: node script/gen_shared.mjs [--check]'); process.exit(2); }
const model = JSON.parse(readFileSync(join(root, 'shared/energy-model.json'), 'utf8'));
const messages = JSON.parse(readFileSync(join(root, 'shared/messages.json'), 'utf8'));
const header = (source) => `// Generated by script/gen_shared.mjs from ${source}. Do not edit; run npm run gen:shared.\n`;

const locales = Object.keys(messages);
for (const locale of locales) {
  const missing = Object.keys(messages.en).filter(key => !(key in messages[locale]));
  const extra = Object.keys(messages[locale]).filter(key => !(key in messages.en));
  if (missing.length || extra.length) { console.error(`messages.json: locale ${locale} differs from en: ${[...missing, ...extra].join(', ')}`); process.exit(1); }
}

const identifier = /^[a-z][A-Za-z0-9]*$/;
const upper = (key) => key[0].toUpperCase() + key.slice(1);
const swiftString = (text) => `"${text.replaceAll('\\', '\\\\').replaceAll('"', '\\"').replaceAll('\n', '\\n')}"`;
function swiftType(value, integer) {
  if (typeof value === 'string') return 'String';
  if (typeof value === 'number') return integer ? 'Int' : 'Double';
  if (Array.isArray(value)) return `[${swiftType(value[0] ?? 0, integer)}]`;
  throw new Error(`Unsupported value ${JSON.stringify(value)}`);
}
function swiftValue(value) {
  if (typeof value === 'string') return swiftString(value);
  if (Array.isArray(value)) return `[${value.map(swiftValue).join(', ')}]`;
  return String(value);
}
function swiftEnum(name, object, indent) {
  const pad = ' '.repeat(indent), lines = [`${pad}public enum ${name} {`];
  for (const [key, value] of Object.entries(object)) {
    if (!identifier.test(key)) throw new Error(`energy-model.json: ${key} is not a valid identifier`);
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      if (Object.keys(value).every(k => identifier.test(k))) { lines.push(...swiftEnum(upper(key), value, indent + 4)); continue; }
      // Keys such as equation IDs are not identifiers: emit a dictionary of integer lists.
      const entries = Object.entries(value).map(([k, v]) => `${pad}        ${swiftString(k)}: ${swiftValue(v)},`);
      lines.push(`${pad}    public static let ${key}: [String: ${swiftType(Object.values(value)[0], true)}] = [`, ...entries, `${pad}    ]`);
      continue;
    }
    lines.push(`${pad}    public static let ${key}: ${swiftType(value, key === 'version')} = ${swiftValue(value)}`);
  }
  lines.push(`${pad}}`); return lines;
}
const outputs = {
  'packages/core/src/generated/model.ts': header('shared/energy-model.json')
    + `export const model = ${JSON.stringify(model, null, 2)} as const;\n`,
  'packages/core/src/generated/messages.ts': header('shared/messages.json')
    + `export const messages = ${JSON.stringify(messages, null, 2)} as const;\n`
    + 'export type Locale = keyof typeof messages;\nexport type MessageKey = keyof typeof messages.en;\n',
  'packages/swift-core/Sources/PurrtionCore/Generated/Model.swift': header('shared/energy-model.json')
    + swiftEnum('EnergyModel', model, 0).join('\n') + '\n',
  'packages/swift-core/Sources/PurrtionCore/Generated/Messages.swift': header('shared/messages.json')
    + 'public enum Messages {\n'
    + locales.map(locale => `    public static let ${locale}: [String: String] = [\n`
      + Object.entries(messages[locale]).map(([k, v]) => `        ${swiftString(k)}: ${swiftString(v)},\n`).join('') + '    ]\n').join('')
    + '}\n',
};
let drift = false;
for (const [path, content] of Object.entries(outputs)) {
  const target = join(root, path);
  if (mode === '--check') {
    if (!existsSync(target) || readFileSync(target, 'utf8') !== content) { console.error(`Generated file drift: ${path}. Run npm run gen:shared.`); drift = true; }
  } else { mkdirSync(dirname(target), { recursive: true }); writeFileSync(target, content); }
}
if (drift) process.exit(1);
